# Generated by Django 3.2.5 on 2021-07-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=50)),
                ('hideName', models.BooleanField()),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mediaForm/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hideName', models.BooleanField()),
                ('writer', models.CharField(max_length=50)),
                ('body', models.TextField(verbose_name='댓글')),
                ('pub_date', models.DateTimeField()),
                ('comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crudSample.comment')),
                ('postId', models.ForeignKey(db_column='postId', on_delete=django.db.models.deletion.CASCADE, to='crudSample.post')),
            ],
        ),
    ]
